// seed.js — ejecutar para poblar Firestore con 1000 personas
// Uso: node seed.js
// Requiere serviceAccountKey.json en la misma carpeta

import { initializeApp, cert } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const serviceAccount = require('./serviceAccountKey.json');

initializeApp({ credential: cert(serviceAccount) });
const db = getFirestore();

const PEOPLE = [
  // SPORTS
  { name:"Lionel Messi",            category:"Sports",     country:"Argentina" },
  { name:"Cristiano Ronaldo",       category:"Sports",     country:"Portugal" },
  { name:"Michael Jordan",          category:"Sports",     country:"USA" },
  { name:"Muhammad Ali",            category:"Sports",     country:"USA" },
  { name:"Usain Bolt",              category:"Sports",     country:"Jamaica" },
  { name:"Roger Federer",           category:"Sports",     country:"Switzerland" },
  { name:"Rafael Nadal",            category:"Sports",     country:"Spain" },
  { name:"Novak Djokovic",          category:"Sports",     country:"Serbia" },
  { name:"Serena Williams",         category:"Sports",     country:"USA" },
  { name:"Tiger Woods",             category:"Sports",     country:"USA" },
  { name:"LeBron James",            category:"Sports",     country:"USA" },
  { name:"Kobe Bryant",             category:"Sports",     country:"USA" },
  { name:"Neymar Jr.",              category:"Sports",     country:"Brazil" },
  { name:"Ronaldinho",              category:"Sports",     country:"Brazil" },
  { name:"Pelé",                    category:"Sports",     country:"Brazil" },
  { name:"Diego Maradona",          category:"Sports",     country:"Argentina" },
  { name:"Zinedine Zidane",         category:"Sports",     country:"France" },
  { name:"Ronaldo Nazário",         category:"Sports",     country:"Brazil" },
  { name:"Zlatan Ibrahimović",      category:"Sports",     country:"Sweden" },
  { name:"David Beckham",           category:"Sports",     country:"UK" },
  { name:"Thierry Henry",           category:"Sports",     country:"France" },
  { name:"Andrés Iniesta",          category:"Sports",     country:"Spain" },
  { name:"Xavi Hernández",          category:"Sports",     country:"Spain" },
  { name:"Luka Modrić",             category:"Sports",     country:"Croatia" },
  { name:"Kylian Mbappé",           category:"Sports",     country:"France" },
  { name:"Erling Haaland",          category:"Sports",     country:"Norway" },
  { name:"Vinicius Jr.",            category:"Sports",     country:"Brazil" },
  { name:"Mohamed Salah",           category:"Sports",     country:"Egypt" },
  { name:"Harry Kane",              category:"Sports",     country:"UK" },
  { name:"Kevin De Bruyne",         category:"Sports",     country:"Belgium" },
  { name:"Robert Lewandowski",      category:"Sports",     country:"Poland" },
  { name:"Karim Benzema",           category:"Sports",     country:"France" },
  { name:"Antoine Griezmann",       category:"Sports",     country:"France" },
  { name:"Pedri",                   category:"Sports",     country:"Spain" },
  { name:"Jude Bellingham",         category:"Sports",     country:"UK" },
  { name:"Stephen Curry",           category:"Sports",     country:"USA" },
  { name:"Kevin Durant",            category:"Sports",     country:"USA" },
  { name:"Giannis Antetokounmpo",   category:"Sports",     country:"Greece" },
  { name:"Shaquille O'Neal",        category:"Sports",     country:"USA" },
  { name:"Magic Johnson",           category:"Sports",     country:"USA" },
  { name:"Larry Bird",              category:"Sports",     country:"USA" },
  { name:"Kareem Abdul-Jabbar",     category:"Sports",     country:"USA" },
  { name:"Scottie Pippen",          category:"Sports",     country:"USA" },
  { name:"Dennis Rodman",           category:"Sports",     country:"USA" },
  { name:"Dirk Nowitzki",           category:"Sports",     country:"Germany" },
  { name:"Luka Dončić",             category:"Sports",     country:"Slovenia" },
  { name:"Nikola Jokić",            category:"Sports",     country:"Serbia" },
  { name:"Joel Embiid",             category:"Sports",     country:"Cameroon" },
  { name:"Patrick Mahomes",         category:"Sports",     country:"USA" },
  { name:"Tom Brady",               category:"Sports",     country:"USA" },
  { name:"Joe Montana",             category:"Sports",     country:"USA" },
  { name:"Bruce Lee",               category:"Sports",     country:"China" },
  { name:"Conor McGregor",          category:"Sports",     country:"Ireland" },
  { name:"Floyd Mayweather",        category:"Sports",     country:"USA" },
  { name:"Mike Tyson",              category:"Sports",     country:"USA" },
  { name:"Canelo Álvarez",          category:"Sports",     country:"Mexico" },
  { name:"Manny Pacquiao",          category:"Sports",     country:"Philippines" },
  { name:"Ayrton Senna",            category:"Sports",     country:"Brazil" },
  { name:"Michael Schumacher",      category:"Sports",     country:"Germany" },
  { name:"Lewis Hamilton",          category:"Sports",     country:"UK" },
  { name:"Max Verstappen",          category:"Sports",     country:"Netherlands" },
  { name:"Fernando Alonso",         category:"Sports",     country:"Spain" },
  { name:"Valentino Rossi",         category:"Sports",     country:"Italy" },
  { name:"Simone Biles",            category:"Sports",     country:"USA" },
  { name:"Michael Phelps",          category:"Sports",     country:"USA" },
  { name:"Carl Lewis",              category:"Sports",     country:"USA" },
  { name:"Jesse Owens",             category:"Sports",     country:"USA" },
  { name:"Eliud Kipchoge",          category:"Sports",     country:"Kenya" },
  { name:"Steffi Graf",             category:"Sports",     country:"Germany" },
  { name:"Martina Navratilova",     category:"Sports",     country:"Czech Republic" },
  { name:"Billie Jean King",        category:"Sports",     country:"USA" },
  { name:"Venus Williams",          category:"Sports",     country:"USA" },
  { name:"Maria Sharapova",         category:"Sports",     country:"Russia" },
  { name:"Pete Sampras",            category:"Sports",     country:"USA" },
  { name:"Andre Agassi",            category:"Sports",     country:"USA" },
  { name:"Carlos Alcaraz",          category:"Sports",     country:"Spain" },
  { name:"Iga Świątek",             category:"Sports",     country:"Poland" },
  { name:"Naomi Osaka",             category:"Sports",     country:"Japan" },
  { name:"Babe Ruth",               category:"Sports",     country:"USA" },
  { name:"Wayne Gretzky",           category:"Sports",     country:"Canada" },
  { name:"Sidney Crosby",           category:"Sports",     country:"Canada" },
  { name:"Jack Nicklaus",           category:"Sports",     country:"USA" },
  { name:"Rory McIlroy",            category:"Sports",     country:"Ireland" },
  { name:"Jon Jones",               category:"Sports",     country:"USA" },
  { name:"Nadia Comaneci",          category:"Sports",     country:"Romania" },
  { name:"Haile Gebrselassie",      category:"Sports",     country:"Ethiopia" },
  { name:"Mo Farah",                category:"Sports",     country:"UK" },
  { name:"Dwyane Wade",             category:"Sports",     country:"USA" },
  { name:"Chris Paul",              category:"Sports",     country:"USA" },
  { name:"James Harden",            category:"Sports",     country:"USA" },
  { name:"Jayson Tatum",            category:"Sports",     country:"USA" },
  { name:"Peyton Manning",          category:"Sports",     country:"USA" },
  { name:"Jerry Rice",              category:"Sports",     country:"USA" },
  { name:"Gavi",                    category:"Sports",     country:"Spain" },
  { name:"Virgil van Dijk",         category:"Sports",     country:"Netherlands" },

  // MUSIC
  { name:"Michael Jackson",         category:"Music",      country:"USA" },
  { name:"Elvis Presley",           category:"Music",      country:"USA" },
  { name:"The Beatles",             category:"Music",      country:"UK" },
  { name:"Bob Dylan",               category:"Music",      country:"USA" },
  { name:"David Bowie",             category:"Music",      country:"UK" },
  { name:"Freddie Mercury",         category:"Music",      country:"UK" },
  { name:"Jimi Hendrix",            category:"Music",      country:"USA" },
  { name:"Bob Marley",              category:"Music",      country:"Jamaica" },
  { name:"Taylor Swift",            category:"Music",      country:"USA" },
  { name:"Beyoncé",                 category:"Music",      country:"USA" },
  { name:"Rihanna",                 category:"Music",      country:"Barbados" },
  { name:"Adele",                   category:"Music",      country:"UK" },
  { name:"Ed Sheeran",              category:"Music",      country:"UK" },
  { name:"Justin Bieber",           category:"Music",      country:"Canada" },
  { name:"Drake",                   category:"Music",      country:"Canada" },
  { name:"Eminem",                  category:"Music",      country:"USA" },
  { name:"Jay-Z",                   category:"Music",      country:"USA" },
  { name:"Kanye West",              category:"Music",      country:"USA" },
  { name:"Kendrick Lamar",          category:"Music",      country:"USA" },
  { name:"The Weeknd",              category:"Music",      country:"Canada" },
  { name:"Bruno Mars",              category:"Music",      country:"USA" },
  { name:"Ariana Grande",           category:"Music",      country:"USA" },
  { name:"Lady Gaga",               category:"Music",      country:"USA" },
  { name:"Katy Perry",              category:"Music",      country:"USA" },
  { name:"Shakira",                 category:"Music",      country:"Colombia" },
  { name:"Bad Bunny",               category:"Music",      country:"Puerto Rico" },
  { name:"J Balvin",                category:"Music",      country:"Colombia" },
  { name:"Daddy Yankee",            category:"Music",      country:"Puerto Rico" },
  { name:"Enrique Iglesias",        category:"Music",      country:"Spain" },
  { name:"Ricky Martin",            category:"Music",      country:"Puerto Rico" },
  { name:"Jennifer Lopez",          category:"Music",      country:"USA" },
  { name:"Celine Dion",             category:"Music",      country:"Canada" },
  { name:"Whitney Houston",         category:"Music",      country:"USA" },
  { name:"Mariah Carey",            category:"Music",      country:"USA" },
  { name:"Madonna",                 category:"Music",      country:"USA" },
  { name:"Britney Spears",          category:"Music",      country:"USA" },
  { name:"Billie Eilish",           category:"Music",      country:"USA" },
  { name:"Olivia Rodrigo",          category:"Music",      country:"USA" },
  { name:"Dua Lipa",                category:"Music",      country:"UK" },
  { name:"Harry Styles",            category:"Music",      country:"UK" },
  { name:"Coldplay",                category:"Music",      country:"UK" },
  { name:"U2",                      category:"Music",      country:"Ireland" },
  { name:"AC/DC",                   category:"Music",      country:"Australia" },
  { name:"Metallica",               category:"Music",      country:"USA" },
  { name:"Guns N' Roses",           category:"Music",      country:"USA" },
  { name:"Nirvana",                 category:"Music",      country:"USA" },
  { name:"Bruce Springsteen",       category:"Music",      country:"USA" },
  { name:"Prince",                  category:"Music",      country:"USA" },
  { name:"Frank Sinatra",           category:"Music",      country:"USA" },
  { name:"Stevie Wonder",           category:"Music",      country:"USA" },
  { name:"Ray Charles",             category:"Music",      country:"USA" },
  { name:"Aretha Franklin",         category:"Music",      country:"USA" },
  { name:"James Brown",             category:"Music",      country:"USA" },
  { name:"Tina Turner",             category:"Music",      country:"USA" },
  { name:"Johnny Cash",             category:"Music",      country:"USA" },
  { name:"Dolly Parton",            category:"Music",      country:"USA" },
  { name:"Elton John",              category:"Music",      country:"UK" },
  { name:"Paul McCartney",          category:"Music",      country:"UK" },
  { name:"John Lennon",             category:"Music",      country:"UK" },
  { name:"Eric Clapton",            category:"Music",      country:"UK" },
  { name:"Amy Winehouse",           category:"Music",      country:"UK" },
  { name:"Nicki Minaj",             category:"Music",      country:"Trinidad and Tobago" },
  { name:"Cardi B",                 category:"Music",      country:"USA" },
  { name:"Billie Eilish",           category:"Music",      country:"USA" },
  { name:"Travis Scott",            category:"Music",      country:"USA" },
  { name:"Lil Wayne",               category:"Music",      country:"USA" },
  { name:"Snoop Dogg",              category:"Music",      country:"USA" },
  { name:"Dr. Dre",                 category:"Music",      country:"USA" },
  { name:"Tupac Shakur",            category:"Music",      country:"USA" },
  { name:"The Notorious B.I.G.",    category:"Music",      country:"USA" },
  { name:"Justin Timberlake",       category:"Music",      country:"USA" },
  { name:"Usher",                   category:"Music",      country:"USA" },
  { name:"Alicia Keys",             category:"Music",      country:"USA" },
  { name:"John Legend",             category:"Music",      country:"USA" },
  { name:"ABBA",                    category:"Music",      country:"Sweden" },
  { name:"Avicii",                  category:"Music",      country:"Sweden" },
  { name:"Daft Punk",               category:"Music",      country:"France" },
  { name:"David Guetta",            category:"Music",      country:"France" },
  { name:"Tiësto",                  category:"Music",      country:"Netherlands" },
  { name:"Martin Garrix",           category:"Music",      country:"Netherlands" },
  { name:"Calvin Harris",           category:"Music",      country:"UK" },
  { name:"Stormzy",                 category:"Music",      country:"UK" },
  { name:"Burna Boy",               category:"Music",      country:"Nigeria" },
  { name:"Wizkid",                  category:"Music",      country:"Nigeria" },
  { name:"BTS",                     category:"Music",      country:"South Korea" },
  { name:"BLACKPINK",               category:"Music",      country:"South Korea" },
  { name:"PSY",                     category:"Music",      country:"South Korea" },
  { name:"A.R. Rahman",             category:"Music",      country:"India" },
  { name:"Lata Mangeshkar",         category:"Music",      country:"India" },
  { name:"Led Zeppelin",            category:"Music",      country:"UK" },
  { name:"The Rolling Stones",      category:"Music",      country:"UK" },
  { name:"Pink Floyd",              category:"Music",      country:"UK" },
  { name:"Post Malone",             category:"Music",      country:"USA" },
  { name:"Maluma",                  category:"Music",      country:"Colombia" },
  { name:"Ozuna",                   category:"Music",      country:"Puerto Rico" },
  { name:"Sia",                     category:"Music",      country:"Australia" },
  { name:"Kylie Minogue",           category:"Music",      country:"Australia" },
  { name:"Stromae",                 category:"Music",      country:"Belgium" },
  { name:"50 Cent",                 category:"Music",      country:"USA" },
  { name:"Lorde",                   category:"Music",      country:"New Zealand" },
  { name:"Sam Smith",               category:"Music",      country:"UK" },
  { name:"Doja Cat",                category:"Music",      country:"USA" },
  { name:"SZA",                     category:"Music",      country:"USA" },
  { name:"Rod Stewart",             category:"Music",      country:"UK" },
  { name:"Mick Jagger",             category:"Music",      country:"UK" },
  { name:"Kurt Cobain",             category:"Music",      country:"USA" },
  { name:"Christina Aguilera",      category:"Music",      country:"USA" },
  { name:"Pharrell Williams",       category:"Music",      country:"USA" },
  { name:"Zara Larsson",            category:"Music",      country:"Sweden" },

  // SCIENCE
  { name:"Albert Einstein",         category:"Science",    country:"Germany" },
  { name:"Isaac Newton",            category:"Science",    country:"UK" },
  { name:"Charles Darwin",          category:"Science",    country:"UK" },
  { name:"Marie Curie",             category:"Science",    country:"Poland" },
  { name:"Nikola Tesla",            category:"Science",    country:"Serbia" },
  { name:"Stephen Hawking",         category:"Science",    country:"UK" },
  { name:"Galileo Galilei",         category:"Science",    country:"Italy" },
  { name:"Louis Pasteur",           category:"Science",    country:"France" },
  { name:"Max Planck",              category:"Science",    country:"Germany" },
  { name:"Niels Bohr",              category:"Science",    country:"Denmark" },
  { name:"Richard Feynman",         category:"Science",    country:"USA" },
  { name:"Carl Sagan",              category:"Science",    country:"USA" },
  { name:"Neil deGrasse Tyson",     category:"Science",    country:"USA" },
  { name:"Jane Goodall",            category:"Science",    country:"UK" },
  { name:"Rosalind Franklin",       category:"Science",    country:"UK" },
  { name:"Ada Lovelace",            category:"Science",    country:"UK" },
  { name:"Alan Turing",             category:"Science",    country:"UK" },
  { name:"James Watson",            category:"Science",    country:"USA" },
  { name:"Gregor Mendel",           category:"Science",    country:"Czech Republic" },
  { name:"Ernest Rutherford",       category:"Science",    country:"New Zealand" },
  { name:"Werner Heisenberg",       category:"Science",    country:"Germany" },
  { name:"Erwin Schrödinger",       category:"Science",    country:"Austria" },
  { name:"Enrico Fermi",            category:"Science",    country:"Italy" },
  { name:"Robert Oppenheimer",      category:"Science",    country:"USA" },
  { name:"Alexander Fleming",       category:"Science",    country:"UK" },
  { name:"Jonas Salk",              category:"Science",    country:"USA" },
  { name:"Sigmund Freud",           category:"Science",    country:"Austria" },
  { name:"Carl Jung",               category:"Science",    country:"Switzerland" },
  { name:"Srinivasa Ramanujan",     category:"Science",    country:"India" },
  { name:"Archimedes",              category:"Science",    country:"Greece" },
  { name:"Copernicus",              category:"Science",    country:"Poland" },
  { name:"Johannes Kepler",         category:"Science",    country:"Germany" },
  { name:"Michael Faraday",         category:"Science",    country:"UK" },
  { name:"Dmitri Mendeleev",        category:"Science",    country:"Russia" },
  { name:"Alfred Nobel",            category:"Science",    country:"Sweden" },
  { name:"Grace Hopper",            category:"Science",    country:"USA" },
  { name:"Michio Kaku",             category:"Science",    country:"USA" },
  { name:"Ivan Pavlov",             category:"Science",    country:"Russia" },
  { name:"Louis de Broglie",        category:"Science",    country:"France" },
  { name:"Antoine Lavoisier",       category:"Science",    country:"France" },
  { name:"Edward Jenner",           category:"Science",    country:"UK" },
  { name:"William Harvey",          category:"Science",    country:"UK" },
  { name:"Leonhard Euler",          category:"Science",    country:"Switzerland" },
  { name:"Carl Friedrich Gauss",    category:"Science",    country:"Germany" },
  { name:"Blaise Pascal",           category:"Science",    country:"France" },
  { name:"James Clerk Maxwell",     category:"Science",    country:"UK" },
  { name:"John von Neumann",        category:"Science",    country:"Hungary" },
  { name:"Francis Crick",           category:"Science",    country:"UK" },

  // TECHNOLOGY
  { name:"Steve Jobs",              category:"Technology", country:"USA" },
  { name:"Bill Gates",              category:"Technology", country:"USA" },
  { name:"Elon Musk",               category:"Technology", country:"USA" },
  { name:"Mark Zuckerberg",         category:"Technology", country:"USA" },
  { name:"Jeff Bezos",              category:"Technology", country:"USA" },
  { name:"Larry Page",              category:"Technology", country:"USA" },
  { name:"Sergey Brin",             category:"Technology", country:"USA" },
  { name:"Jack Dorsey",             category:"Technology", country:"USA" },
  { name:"Tim Cook",                category:"Technology", country:"USA" },
  { name:"Sundar Pichai",           category:"Technology", country:"India" },
  { name:"Satya Nadella",           category:"Technology", country:"India" },
  { name:"Jensen Huang",            category:"Technology", country:"Taiwan" },
  { name:"Jack Ma",                 category:"Technology", country:"China" },
  { name:"Sam Altman",              category:"Technology", country:"USA" },
  { name:"Demis Hassabis",          category:"Technology", country:"UK" },
  { name:"Linus Torvalds",          category:"Technology", country:"Finland" },
  { name:"Tim Berners-Lee",         category:"Technology", country:"UK" },
  { name:"Larry Ellison",           category:"Technology", country:"USA" },
  { name:"Peter Thiel",             category:"Technology", country:"USA" },
  { name:"Reid Hoffman",            category:"Technology", country:"USA" },
  { name:"Marc Andreessen",         category:"Technology", country:"USA" },
  { name:"Evan Spiegel",            category:"Technology", country:"USA" },
  { name:"Kevin Systrom",           category:"Technology", country:"USA" },
  { name:"Michael Dell",            category:"Technology", country:"USA" },
  { name:"Gordon Moore",            category:"Technology", country:"USA" },
  { name:"Charles Babbage",         category:"Technology", country:"UK" },
  { name:"Dennis Ritchie",          category:"Technology", country:"USA" },
  { name:"Donald Knuth",            category:"Technology", country:"USA" },
  { name:"Vint Cerf",               category:"Technology", country:"USA" },
  { name:"Zhang Yiming",            category:"Technology", country:"China" },
  { name:"Pony Ma",                 category:"Technology", country:"China" },
  { name:"Ren Zhengfei",            category:"Technology", country:"China" },
  { name:"Brian Chesky",            category:"Technology", country:"USA" },
  { name:"Travis Kalanick",         category:"Technology", country:"USA" },
  { name:"Reed Hastings",           category:"Technology", country:"USA" },

  // CINEMA
  { name:"Marilyn Monroe",          category:"Cinema",     country:"USA" },
  { name:"Charlie Chaplin",         category:"Cinema",     country:"UK" },
  { name:"Audrey Hepburn",          category:"Cinema",     country:"Belgium" },
  { name:"Marlon Brando",           category:"Cinema",     country:"USA" },
  { name:"James Dean",              category:"Cinema",     country:"USA" },
  { name:"Jack Nicholson",          category:"Cinema",     country:"USA" },
  { name:"Al Pacino",               category:"Cinema",     country:"USA" },
  { name:"Robert De Niro",          category:"Cinema",     country:"USA" },
  { name:"Meryl Streep",            category:"Cinema",     country:"USA" },
  { name:"Cate Blanchett",          category:"Cinema",     country:"Australia" },
  { name:"Elizabeth Taylor",        category:"Cinema",     country:"UK" },
  { name:"Sophia Loren",            category:"Cinema",     country:"Italy" },
  { name:"Brigitte Bardot",         category:"Cinema",     country:"France" },
  { name:"Humphrey Bogart",         category:"Cinema",     country:"USA" },
  { name:"Clark Gable",             category:"Cinema",     country:"USA" },
  { name:"Cary Grant",              category:"Cinema",     country:"UK" },
  { name:"Paul Newman",             category:"Cinema",     country:"USA" },
  { name:"Clint Eastwood",          category:"Cinema",     country:"USA" },
  { name:"Sylvester Stallone",      category:"Cinema",     country:"USA" },
  { name:"Arnold Schwarzenegger",   category:"Cinema",     country:"Austria" },
  { name:"Tom Hanks",               category:"Cinema",     country:"USA" },
  { name:"Tom Cruise",              category:"Cinema",     country:"USA" },
  { name:"Brad Pitt",               category:"Cinema",     country:"USA" },
  { name:"George Clooney",          category:"Cinema",     country:"USA" },
  { name:"Leonardo DiCaprio",       category:"Cinema",     country:"USA" },
  { name:"Johnny Depp",             category:"Cinema",     country:"USA" },
  { name:"Denzel Washington",       category:"Cinema",     country:"USA" },
  { name:"Morgan Freeman",          category:"Cinema",     country:"USA" },
  { name:"Samuel L. Jackson",       category:"Cinema",     country:"USA" },
  { name:"Robin Williams",          category:"Cinema",     country:"USA" },
  { name:"Keanu Reeves",            category:"Cinema",     country:"Canada" },
  { name:"Dwayne Johnson",          category:"Cinema",     country:"USA" },
  { name:"Ryan Reynolds",           category:"Cinema",     country:"Canada" },
  { name:"Robert Downey Jr.",       category:"Cinema",     country:"USA" },
  { name:"Scarlett Johansson",      category:"Cinema",     country:"USA" },
  { name:"Jennifer Lawrence",       category:"Cinema",     country:"USA" },
  { name:"Emma Watson",             category:"Cinema",     country:"UK" },
  { name:"Natalie Portman",         category:"Cinema",     country:"Israel" },
  { name:"Angelina Jolie",          category:"Cinema",     country:"USA" },
  { name:"Julia Roberts",           category:"Cinema",     country:"USA" },
  { name:"Nicole Kidman",           category:"Cinema",     country:"Australia" },
  { name:"Charlize Theron",         category:"Cinema",     country:"South Africa" },
  { name:"Halle Berry",             category:"Cinema",     country:"USA" },
  { name:"Viola Davis",             category:"Cinema",     country:"USA" },
  { name:"Chadwick Boseman",        category:"Cinema",     country:"USA" },
  { name:"Idris Elba",              category:"Cinema",     country:"UK" },
  { name:"Benedict Cumberbatch",    category:"Cinema",     country:"UK" },
  { name:"Hugh Jackman",            category:"Cinema",     country:"Australia" },
  { name:"Heath Ledger",            category:"Cinema",     country:"Australia" },
  { name:"Joaquin Phoenix",         category:"Cinema",     country:"USA" },
  { name:"Christian Bale",          category:"Cinema",     country:"UK" },
  { name:"Anthony Hopkins",         category:"Cinema",     country:"UK" },
  { name:"Sean Connery",            category:"Cinema",     country:"UK" },
  { name:"Harrison Ford",           category:"Cinema",     country:"USA" },
  { name:"Steven Spielberg",        category:"Cinema",     country:"USA" },
  { name:"Martin Scorsese",         category:"Cinema",     country:"USA" },
  { name:"Stanley Kubrick",         category:"Cinema",     country:"USA" },
  { name:"Alfred Hitchcock",        category:"Cinema",     country:"UK" },
  { name:"Quentin Tarantino",       category:"Cinema",     country:"USA" },
  { name:"Christopher Nolan",       category:"Cinema",     country:"UK" },
  { name:"James Cameron",           category:"Cinema",     country:"Canada" },
  { name:"George Lucas",            category:"Cinema",     country:"USA" },
  { name:"Pedro Almodóvar",         category:"Cinema",     country:"Spain" },
  { name:"Federico Fellini",        category:"Cinema",     country:"Italy" },
  { name:"Akira Kurosawa",          category:"Cinema",     country:"Japan" },
  { name:"Ingmar Bergman",          category:"Cinema",     country:"Sweden" },
  { name:"Bong Joon-ho",            category:"Cinema",     country:"South Korea" },
  { name:"Alfonso Cuarón",          category:"Cinema",     country:"Mexico" },
  { name:"Guillermo del Toro",      category:"Cinema",     country:"Mexico" },
  { name:"Will Smith",              category:"Cinema",     country:"USA" },
  { name:"Eddie Murphy",            category:"Cinema",     country:"USA" },
  { name:"Jim Carrey",              category:"Cinema",     country:"Canada" },
  { name:"Adam Sandler",            category:"Cinema",     country:"USA" },
  { name:"Chris Evans",             category:"Cinema",     country:"USA" },
  { name:"Chris Hemsworth",         category:"Cinema",     country:"Australia" },
  { name:"Lupita Nyong'o",          category:"Cinema",     country:"Kenya" },
  { name:"Woody Allen",             category:"Cinema",     country:"USA" },
  { name:"Francis Ford Coppola",    category:"Cinema",     country:"USA" },
  { name:"Ridley Scott",            category:"Cinema",     country:"UK" },
  { name:"Tim Burton",              category:"Cinema",     country:"USA" },
  { name:"Grace Kelly",             category:"Cinema",     country:"USA" },
  { name:"Katharine Hepburn",       category:"Cinema",     country:"USA" },
  { name:"Alejandro González Iñárritu", category:"Cinema", country:"Mexico" },

  // POLITICS
  { name:"Barack Obama",            category:"Politics",   country:"USA" },
  { name:"Donald Trump",            category:"Politics",   country:"USA" },
  { name:"Joe Biden",               category:"Politics",   country:"USA" },
  { name:"Hillary Clinton",         category:"Politics",   country:"USA" },
  { name:"Abraham Lincoln",         category:"Politics",   country:"USA" },
  { name:"John F. Kennedy",         category:"Politics",   country:"USA" },
  { name:"Franklin D. Roosevelt",   category:"Politics",   country:"USA" },
  { name:"George Washington",       category:"Politics",   country:"USA" },
  { name:"Theodore Roosevelt",      category:"Politics",   country:"USA" },
  { name:"Ronald Reagan",           category:"Politics",   country:"USA" },
  { name:"Winston Churchill",       category:"Politics",   country:"UK" },
  { name:"Margaret Thatcher",       category:"Politics",   country:"UK" },
  { name:"Nelson Mandela",          category:"Politics",   country:"South Africa" },
  { name:"Vladimir Putin",          category:"Politics",   country:"Russia" },
  { name:"Joseph Stalin",           category:"Politics",   country:"Russia" },
  { name:"Mikhail Gorbachev",       category:"Politics",   country:"Russia" },
  { name:"Vladimir Lenin",          category:"Politics",   country:"Russia" },
  { name:"Mao Zedong",              category:"Politics",   country:"China" },
  { name:"Xi Jinping",              category:"Politics",   country:"China" },
  { name:"Deng Xiaoping",           category:"Politics",   country:"China" },
  { name:"Adolf Hitler",            category:"Politics",   country:"Germany" },
  { name:"Angela Merkel",           category:"Politics",   country:"Germany" },
  { name:"Charles de Gaulle",       category:"Politics",   country:"France" },
  { name:"Emmanuel Macron",         category:"Politics",   country:"France" },
  { name:"Napoleon Bonaparte",      category:"Politics",   country:"France" },
  { name:"Mahatma Gandhi",          category:"Politics",   country:"India" },
  { name:"Jawaharlal Nehru",        category:"Politics",   country:"India" },
  { name:"Narendra Modi",           category:"Politics",   country:"India" },
  { name:"Indira Gandhi",           category:"Politics",   country:"India" },
  { name:"Fidel Castro",            category:"Politics",   country:"Cuba" },
  { name:"Che Guevara",             category:"Politics",   country:"Argentina" },
  { name:"Simón Bolívar",           category:"Politics",   country:"Venezuela" },
  { name:"Lula da Silva",           category:"Politics",   country:"Brazil" },
  { name:"Francisco Franco",        category:"Politics",   country:"Spain" },
  { name:"Pedro Sánchez",           category:"Politics",   country:"Spain" },
  { name:"Julius Caesar",           category:"Politics",   country:"Italy" },
  { name:"Alexander the Great",     category:"Politics",   country:"Greece" },
  { name:"Cleopatra",               category:"Politics",   country:"Egypt" },
  { name:"Genghis Khan",            category:"Politics",   country:"Mongolia" },
  { name:"Charlemagne",             category:"Politics",   country:"France" },
  { name:"Queen Elizabeth I",       category:"Politics",   country:"UK" },
  { name:"Queen Victoria",          category:"Politics",   country:"UK" },
  { name:"Catherine the Great",     category:"Politics",   country:"Russia" },
  { name:"Louis XIV",               category:"Politics",   country:"France" },
  { name:"Marie Antoinette",        category:"Politics",   country:"France" },
  { name:"Mustafa Kemal Atatürk",   category:"Politics",   country:"Turkey" },
  { name:"Gamal Abdel Nasser",      category:"Politics",   country:"Egypt" },
  { name:"Lee Kuan Yew",            category:"Politics",   country:"Singapore" },
  { name:"Ho Chi Minh",             category:"Politics",   country:"Vietnam" },
  { name:"Benito Mussolini",        category:"Politics",   country:"Italy" },
  { name:"Bill Clinton",            category:"Politics",   country:"USA" },
  { name:"George W. Bush",          category:"Politics",   country:"USA" },
  { name:"Recep Tayyip Erdoğan",    category:"Politics",   country:"Turkey" },
  { name:"Ayatollah Khomeini",      category:"Politics",   country:"Iran" },
  { name:"Yasser Arafat",           category:"Politics",   country:"Palestine" },
  { name:"Kim Jong-un",             category:"Politics",   country:"North Korea" },
  { name:"Hugo Chávez",             category:"Politics",   country:"Venezuela" },
  { name:"Salvador Allende",        category:"Politics",   country:"Chile" },
  { name:"Juan Perón",              category:"Politics",   country:"Argentina" },
  { name:"Otto von Bismarck",       category:"Politics",   country:"Germany" },
  { name:"Kwame Nkrumah",           category:"Politics",   country:"Ghana" },
  { name:"Thomas Sankara",          category:"Politics",   country:"Burkina Faso" },
  { name:"Patrice Lumumba",         category:"Politics",   country:"Congo" },

  // ACTIVISM
  { name:"Martin Luther King Jr.",  category:"Activism",   country:"USA" },
  { name:"Rosa Parks",              category:"Activism",   country:"USA" },
  { name:"Malcolm X",               category:"Activism",   country:"USA" },
  { name:"Harriet Tubman",          category:"Activism",   country:"USA" },
  { name:"Frederick Douglass",      category:"Activism",   country:"USA" },
  { name:"Susan B. Anthony",        category:"Activism",   country:"USA" },
  { name:"Gloria Steinem",          category:"Activism",   country:"USA" },
  { name:"Cesar Chavez",            category:"Activism",   country:"USA" },
  { name:"Angela Davis",            category:"Activism",   country:"USA" },
  { name:"Malala Yousafzai",        category:"Activism",   country:"Pakistan" },
  { name:"Greta Thunberg",          category:"Activism",   country:"Sweden" },
  { name:"Wangari Maathai",         category:"Activism",   country:"Kenya" },
  { name:"Desmond Tutu",            category:"Activism",   country:"South Africa" },
  { name:"Mother Teresa",           category:"Activism",   country:"Albania" },
  { name:"Joan of Arc",             category:"Activism",   country:"France" },
  { name:"Emmeline Pankhurst",      category:"Activism",   country:"UK" },
  { name:"Noam Chomsky",            category:"Activism",   country:"USA" },
  { name:"Rigoberta Menchú",        category:"Activism",   country:"Guatemala" },
  { name:"Shirin Ebadi",            category:"Activism",   country:"Iran" },
  { name:"Coretta Scott King",      category:"Activism",   country:"USA" },
  { name:"Harvey Milk",             category:"Activism",   country:"USA" },
  { name:"Aung San Suu Kyi",        category:"Activism",   country:"Myanmar" },
  { name:"Ai Weiwei",               category:"Activism",   country:"China" },
  { name:"Albert Schweitzer",       category:"Activism",   country:"France" },

  // LITERATURE
  { name:"William Shakespeare",     category:"Literature", country:"UK" },
  { name:"Homer",                   category:"Literature", country:"Greece" },
  { name:"Dante Alighieri",         category:"Literature", country:"Italy" },
  { name:"Miguel de Cervantes",     category:"Literature", country:"Spain" },
  { name:"Victor Hugo",             category:"Literature", country:"France" },
  { name:"Marcel Proust",           category:"Literature", country:"France" },
  { name:"Albert Camus",            category:"Literature", country:"France" },
  { name:"Voltaire",                category:"Literature", country:"France" },
  { name:"Leo Tolstoy",             category:"Literature", country:"Russia" },
  { name:"Fyodor Dostoevsky",       category:"Literature", country:"Russia" },
  { name:"Anton Chekhov",           category:"Literature", country:"Russia" },
  { name:"Alexander Pushkin",       category:"Literature", country:"Russia" },
  { name:"Mikhail Bulgakov",        category:"Literature", country:"Russia" },
  { name:"George Orwell",           category:"Literature", country:"UK" },
  { name:"Charles Dickens",         category:"Literature", country:"UK" },
  { name:"Jane Austen",             category:"Literature", country:"UK" },
  { name:"Virginia Woolf",          category:"Literature", country:"UK" },
  { name:"Oscar Wilde",             category:"Literature", country:"Ireland" },
  { name:"James Joyce",             category:"Literature", country:"Ireland" },
  { name:"Arthur Conan Doyle",      category:"Literature", country:"UK" },
  { name:"Agatha Christie",         category:"Literature", country:"UK" },
  { name:"J.R.R. Tolkien",          category:"Literature", country:"UK" },
  { name:"J.K. Rowling",            category:"Literature", country:"UK" },
  { name:"Mark Twain",              category:"Literature", country:"USA" },
  { name:"Ernest Hemingway",        category:"Literature", country:"USA" },
  { name:"F. Scott Fitzgerald",     category:"Literature", country:"USA" },
  { name:"Edgar Allan Poe",         category:"Literature", country:"USA" },
  { name:"Walt Whitman",            category:"Literature", country:"USA" },
  { name:"Emily Dickinson",         category:"Literature", country:"USA" },
  { name:"Herman Melville",         category:"Literature", country:"USA" },
  { name:"Jack Kerouac",            category:"Literature", country:"USA" },
  { name:"Toni Morrison",           category:"Literature", country:"USA" },
  { name:"Maya Angelou",            category:"Literature", country:"USA" },
  { name:"Gabriel García Márquez",  category:"Literature", country:"Colombia" },
  { name:"Pablo Neruda",            category:"Literature", country:"Chile" },
  { name:"Jorge Luis Borges",       category:"Literature", country:"Argentina" },
  { name:"Mario Vargas Llosa",      category:"Literature", country:"Peru" },
  { name:"Isabel Allende",          category:"Literature", country:"Chile" },
  { name:"Octavio Paz",             category:"Literature", country:"Mexico" },
  { name:"Franz Kafka",             category:"Literature", country:"Czech Republic" },
  { name:"Thomas Mann",             category:"Literature", country:"Germany" },
  { name:"Hermann Hesse",           category:"Literature", country:"Germany" },
  { name:"Stefan Zweig",            category:"Literature", country:"Austria" },
  { name:"Naguib Mahfouz",          category:"Literature", country:"Egypt" },
  { name:"Chinua Achebe",           category:"Literature", country:"Nigeria" },
  { name:"Rabindranath Tagore",     category:"Literature", country:"India" },
  { name:"Haruki Murakami",         category:"Literature", country:"Japan" },
  { name:"Yukio Mishima",           category:"Literature", country:"Japan" },
  { name:"Milan Kundera",           category:"Literature", country:"Czech Republic" },
  { name:"Czesław Miłosz",          category:"Literature", country:"Poland" },
  { name:"Gustave Flaubert",        category:"Literature", country:"France" },
  { name:"Johann Wolfgang von Goethe", category:"Literature", country:"Germany" },
  { name:"John Steinbeck",          category:"Literature", country:"USA" },
  { name:"William Faulkner",        category:"Literature", country:"USA" },
  { name:"Julio Cortázar",          category:"Literature", country:"Argentina" },
  { name:"Carlos Fuentes",          category:"Literature", country:"Mexico" },
  { name:"Wisława Szymborska",      category:"Literature", country:"Poland" },
  { name:"Wole Soyinka",            category:"Literature", country:"Nigeria" },
  { name:"Arundhati Roy",           category:"Literature", country:"India" },
  { name:"Mo Yan",                  category:"Literature", country:"China" },

  // ART
  { name:"Leonardo da Vinci",       category:"Art",        country:"Italy" },
  { name:"Michelangelo",            category:"Art",        country:"Italy" },
  { name:"Raphael",                 category:"Art",        country:"Italy" },
  { name:"Caravaggio",              category:"Art",        country:"Italy" },
  { name:"Pablo Picasso",           category:"Art",        country:"Spain" },
  { name:"Salvador Dalí",           category:"Art",        country:"Spain" },
  { name:"Francisco Goya",          category:"Art",        country:"Spain" },
  { name:"Diego Velázquez",         category:"Art",        country:"Spain" },
  { name:"Frida Kahlo",             category:"Art",        country:"Mexico" },
  { name:"Diego Rivera",            category:"Art",        country:"Mexico" },
  { name:"Vincent van Gogh",        category:"Art",        country:"Netherlands" },
  { name:"Rembrandt",               category:"Art",        country:"Netherlands" },
  { name:"Johannes Vermeer",        category:"Art",        country:"Netherlands" },
  { name:"Claude Monet",            category:"Art",        country:"France" },
  { name:"Pierre-Auguste Renoir",   category:"Art",        country:"France" },
  { name:"Paul Cézanne",            category:"Art",        country:"France" },
  { name:"Henri Matisse",           category:"Art",        country:"France" },
  { name:"Marcel Duchamp",          category:"Art",        country:"France" },
  { name:"Auguste Rodin",           category:"Art",        country:"France" },
  { name:"Paul Gauguin",            category:"Art",        country:"France" },
  { name:"Édouard Manet",           category:"Art",        country:"France" },
  { name:"Edgar Degas",             category:"Art",        country:"France" },
  { name:"Wassily Kandinsky",       category:"Art",        country:"Russia" },
  { name:"Marc Chagall",            category:"Art",        country:"Russia" },
  { name:"Jackson Pollock",         category:"Art",        country:"USA" },
  { name:"Andy Warhol",             category:"Art",        country:"USA" },
  { name:"Jean-Michel Basquiat",    category:"Art",        country:"USA" },
  { name:"Mark Rothko",             category:"Art",        country:"USA" },
  { name:"Georgia O'Keeffe",        category:"Art",        country:"USA" },
  { name:"Edward Hopper",           category:"Art",        country:"USA" },
  { name:"Banksy",                  category:"Art",        country:"UK" },
  { name:"Damien Hirst",            category:"Art",        country:"UK" },
  { name:"David Hockney",           category:"Art",        country:"UK" },
  { name:"Francis Bacon",           category:"Art",        country:"UK" },
  { name:"Albrecht Dürer",          category:"Art",        country:"Germany" },
  { name:"Peter Paul Rubens",       category:"Art",        country:"Belgium" },
  { name:"Jan van Eyck",            category:"Art",        country:"Belgium" },
  { name:"Yayoi Kusama",            category:"Art",        country:"Japan" },
  { name:"Hokusai",                 category:"Art",        country:"Japan" },
  { name:"Sandro Botticelli",       category:"Art",        country:"Italy" },
  { name:"Joan Miró",               category:"Art",        country:"Spain" },
  { name:"Titian",                  category:"Art",        country:"Italy" },
  { name:"El Greco",                category:"Art",        country:"Greece" },

  // PHILOSOPHY
  { name:"Socrates",                category:"Philosophy", country:"Greece" },
  { name:"Plato",                   category:"Philosophy", country:"Greece" },
  { name:"Aristotle",               category:"Philosophy", country:"Greece" },
  { name:"Epicurus",                category:"Philosophy", country:"Greece" },
  { name:"Marcus Aurelius",         category:"Philosophy", country:"Italy" },
  { name:"Confucius",               category:"Philosophy", country:"China" },
  { name:"Lao Tzu",                 category:"Philosophy", country:"China" },
  { name:"Sun Tzu",                 category:"Philosophy", country:"China" },
  { name:"Siddhartha Gautama",      category:"Philosophy", country:"Nepal" },
  { name:"Rumi",                    category:"Philosophy", country:"Iran" },
  { name:"Avicenna",                category:"Philosophy", country:"Iran" },
  { name:"Thomas Aquinas",          category:"Philosophy", country:"Italy" },
  { name:"René Descartes",          category:"Philosophy", country:"France" },
  { name:"John Locke",              category:"Philosophy", country:"UK" },
  { name:"David Hume",              category:"Philosophy", country:"UK" },
  { name:"Bertrand Russell",        category:"Philosophy", country:"UK" },
  { name:"Ludwig Wittgenstein",     category:"Philosophy", country:"Austria" },
  { name:"Immanuel Kant",           category:"Philosophy", country:"Germany" },
  { name:"Georg Hegel",             category:"Philosophy", country:"Germany" },
  { name:"Karl Marx",               category:"Philosophy", country:"Germany" },
  { name:"Friedrich Nietzsche",     category:"Philosophy", country:"Germany" },
  { name:"Arthur Schopenhauer",     category:"Philosophy", country:"Germany" },
  { name:"Martin Heidegger",        category:"Philosophy", country:"Germany" },
  { name:"Hannah Arendt",           category:"Philosophy", country:"Germany" },
  { name:"Jean-Paul Sartre",        category:"Philosophy", country:"France" },
  { name:"Michel Foucault",         category:"Philosophy", country:"France" },
  { name:"Simone de Beauvoir",      category:"Philosophy", country:"France" },
  { name:"Søren Kierkegaard",       category:"Philosophy", country:"Denmark" },
  { name:"Seneca",                  category:"Philosophy", country:"Spain" },
  { name:"John Stuart Mill",        category:"Philosophy", country:"UK" },
  { name:"Spinoza",                 category:"Philosophy", country:"Netherlands" },
  { name:"Voltaire",                category:"Philosophy", country:"France" },
  { name:"Jean-Jacques Rousseau",   category:"Philosophy", country:"Switzerland" },
  { name:"Peter Singer",            category:"Philosophy", country:"Australia" },

  // RELIGION
  { name:"Jesus Christ",            category:"Religion",   country:"Palestine" },
  { name:"Prophet Muhammad",        category:"Religion",   country:"Saudi Arabia" },
  { name:"Moses",                   category:"Religion",   country:"Egypt" },
  { name:"Pope Francis",            category:"Religion",   country:"Argentina" },
  { name:"Pope John Paul II",       category:"Religion",   country:"Poland" },
  { name:"Martin Luther",           category:"Religion",   country:"Germany" },
  { name:"Dalai Lama",              category:"Religion",   country:"Tibet" },
  { name:"Swami Vivekananda",       category:"Religion",   country:"India" },
  { name:"Billy Graham",            category:"Religion",   country:"USA" },
  { name:"Mother Teresa",           category:"Religion",   country:"Albania" },

  // INTERNET
  { name:"MrBeast",                 category:"Internet",   country:"USA" },
  { name:"PewDiePie",               category:"Internet",   country:"Sweden" },
  { name:"Ninja",                   category:"Internet",   country:"USA" },
  { name:"Markiplier",              category:"Internet",   country:"USA" },
  { name:"Logan Paul",              category:"Internet",   country:"USA" },
  { name:"Jake Paul",               category:"Internet",   country:"USA" },
  { name:"David Dobrik",            category:"Internet",   country:"Slovakia" },
  { name:"Charli D'Amelio",         category:"Internet",   country:"USA" },
  { name:"Emma Chamberlain",        category:"Internet",   country:"USA" },
  { name:"KSI",                     category:"Internet",   country:"UK" },
  { name:"Pokimane",                category:"Internet",   country:"Canada" },
  { name:"Khaby Lame",              category:"Internet",   country:"Senegal" },
  { name:"Casey Neistat",           category:"Internet",   country:"USA" },
  { name:"Vsauce",                  category:"Internet",   country:"USA" },
  { name:"Kurzgesagt",              category:"Internet",   country:"Germany" },
  { name:"Dude Perfect",            category:"Internet",   country:"USA" },
  { name:"Zach King",               category:"Internet",   country:"USA" },
  { name:"Jacksepticeye",           category:"Internet",   country:"Ireland" },
  { name:"Addison Rae",             category:"Internet",   country:"USA" },
  { name:"Lilly Singh",             category:"Internet",   country:"Canada" },
];

// Remove duplicates
const unique = [];
const seen = new Set();
for (const p of PEOPLE) {
  if (!seen.has(p.name)) { seen.add(p.name); unique.push(p); }
}

async function seed() {
  console.log(`Seeding ${unique.length} people...`);

  // Delete all existing people
  console.log('Deleting existing data...');
  const existing = await db.collection('people').get();
  const delBatch = db.batch();
  existing.docs.forEach(d => delBatch.delete(d.ref));
  if (existing.docs.length > 0) await delBatch.commit();
  console.log(`Deleted ${existing.docs.length} existing records`);

  // Insert in batches of 499
  for (let i = 0; i < unique.length; i += 499) {
    const batch = db.batch();
    const chunk = unique.slice(i, i + 499);
    chunk.forEach(p => {
      const ref = db.collection('people').doc();
      batch.set(ref, { ...p, votes: 0, createdAt: Timestamp.now() });
    });
    await batch.commit();
    console.log(`✓ ${Math.min(i + 499, unique.length)}/${unique.length} personas`);
  }

  console.log(`\n✅ Done! ${unique.length} personas cargadas con 0 votos.`);
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
